swagger: "2.0"
info:
  title: "Spring User Test"
  description: "Users test swagger API"
  version: "1.0.0"
  termsOfService: "http://swagger.io/terms/"
basePath: "/v2"
tags:
- name: "User"
  description: "operations about"
- name: "User info"
  description: "sa"
schemes:
- "https"
consumes:
  - application/json
produces:
  - application/json
paths:
  /user/{userId}:
    get:
      tags:
      - "User"
      summary: "Find user by ID"
      operationId: "getUserById"
      produces:
      - "application/xml"
      - "application/json"
      parameters:
        - name: "userId"
          in: "path"
          required: true
          type: "integer"
          format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/UserResponseDto"
        400:
          description: "Invalid ID supplied"
        404:
          description: "User not found"
  /user:
    post:
      tags:
      - "users"
      summary: "Creates a new user"
      description: "Creates a new user."
      operationId: "createUser"
      consumes:
      - "application/json"
      parameters:
      - in: "body"
        name: "body"
        description: "customer's name"
        required: true
        schema:
          $ref: '#/definitions/UserRequestDto'
      responses:
        201:
          description: "successful operation"
          schema:
            $ref: '#/definitions/UserResponseDto'

definitions:
  UserResponseDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
  UserRequestDto:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      firstName:
        type: "string"
      lastName:
        type: "string"
    required:
      - id
      - firstName
      - lastName
externalDocs:
  description: "Find out more about Swagger"
  url: "http://swagger.io"